from pathlib import Path

from dagrun.workspace import ensure_dagrun_dir, find_project_root
from dagrun.models import PlanMetadata, PlanModel, TaskModel
from dagrun.md2plan import plan_to_yaml_with_header


def test_find_project_root_prefers_git(tmp_path: Path):
    root = tmp_path / "repo"
    nested = root / "a" / "b"
    (root / ".git").mkdir(parents=True)
    nested.mkdir(parents=True)

    assert find_project_root(nested) == root


def test_ensure_dagrun_dir_creates(tmp_path: Path):
    d = ensure_dagrun_dir(tmp_path)
    assert d.exists()
    assert d.is_dir()
    assert d.name == ".dagrun"


def test_plan_header_written():
    plan = PlanModel(
        plan=PlanMetadata(id="X", goal="Y"),
        tasks=[TaskModel(id="T1", title="t", action="a", agent="ag", depends_on=[], files=[], mode="either")],
    )
    out = plan_to_yaml_with_header(plan, source_path=Path("a.md"), ruleset_path=Path("r.yaml"), generator_version="0.1.0")
    assert out.startswith("# Generated by DAGrun")
    assert "# source: a.md" in out
    assert "# ruleset: r.yaml" in out
    assert "\nplan:\n" in out

